// App and game categories list extracted from
// https://support.google.com/googleplay/android-developer/answer/9859673

export const appCategories = [
  'Art and Design',
  'Auto and Vehicles',
  'Beauty',
  'Books and Reference',
  'Business',
  'Comics',
  'Communications',
  'Dating',
  'Education',
  'Entertainment',
  'Events',
  'Finance',
  'Food and Drink',
  'Health and Fitness',
  'House and Home',
  'Libraries and Demo',
  'Lifestyle',
  'Maps and Navigation',
  'Medical',
  'Music and Audio',
  'News and Magazines',
  'Parenting',
  'Personalization',
  'Photography',
  'Productivity',
  'Shopping',
  'Social',
  'Sports',
  'Tools',
  'Travel and Local',
  'Video Players and Editors',
  'Weather',
]

export const gameCategories = [
  'Action',
  'Adventure',
  'Arcade',
  'Board',
  'Card',
  'Casino',
  'Casual',
  'Educational',
  'Music',
  'Puzzle',
  'Racing',
  'Role playing',
  'Simulation',
  'Sports',
  'Strategy',
  'Trivia',
  'Word',
]